name: .NET breakage reproducer

on:
  [push, workflow_dispatch]

jobs:
  dotnet-info:
    name: Run `dotnet --info`
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK 8.0.112
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.112'

      - name: Install required .NET workloads
        run: |
          dotnet workload install android # Replace 'android' with other workloads if needed

      - name: Run `dotnet --info`
        run: dotnet --info

  dotnet-workload-search:
    name: Run `dotnet workload search`
    runs-on: windows-latest
    needs: dotnet-info  # This ensures it runs after the dotnet-info job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK 8.0.112
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.112'

      - name: Install required .NET workloads
        run: |
          dotnet workload install android # Replace 'android' with other workloads if needed

      - name: Run `dotnet workload search`
        run: dotnet workload search
